kind: Service
apiVersion: v1
metadata:
  name: author
  labels:
    app: author
spec:
  type: NodePort
  selector:
    app: author
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: author
  labels:
    app: author
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author
      version: v1
  template:
    metadata:
      labels:
        app: author
        version: v1
    spec:
      containers:
        - name: author
          image: author
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080